# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/flo-k/project_ergasia_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/flo-k/project_ergasia_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flo-k/project_ergasia_1/CMakeFiles /home/flo-k/project_ergasia_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flo-k/project_ergasia_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named CGAL_Qt5_moc_and_resources

# Build rule for target.
CGAL_Qt5_moc_and_resources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Qt5_moc_and_resources
.PHONY : CGAL_Qt5_moc_and_resources

# fast build rule for target.
CGAL_Qt5_moc_and_resources/fast:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build
.PHONY : CGAL_Qt5_moc_and_resources/fast

#=============================================================================
# Target rules for targets named CGAL_Qt5_moc_and_resources_autogen

# Build rule for target.
CGAL_Qt5_moc_and_resources_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Qt5_moc_and_resources_autogen
.PHONY : CGAL_Qt5_moc_and_resources_autogen

# fast build rule for target.
CGAL_Qt5_moc_and_resources_autogen/fast:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build
.PHONY : CGAL_Qt5_moc_and_resources_autogen/fast

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o

.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o

# target to build an object file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i

.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i

# target to preprocess a source file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s

.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s

# target to generate assembly for a file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

qrc_CGAL.o: qrc_CGAL.cpp.o

.PHONY : qrc_CGAL.o

# target to build an object file
qrc_CGAL.cpp.o:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.o
.PHONY : qrc_CGAL.cpp.o

qrc_CGAL.i: qrc_CGAL.cpp.i

.PHONY : qrc_CGAL.i

# target to preprocess a source file
qrc_CGAL.cpp.i:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.i
.PHONY : qrc_CGAL.cpp.i

qrc_CGAL.s: qrc_CGAL.cpp.s

.PHONY : qrc_CGAL.s

# target to generate assembly for a file
qrc_CGAL.cpp.s:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.s
.PHONY : qrc_CGAL.cpp.s

qrc_File.o: qrc_File.cpp.o

.PHONY : qrc_File.o

# target to build an object file
qrc_File.cpp.o:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.o
.PHONY : qrc_File.cpp.o

qrc_File.i: qrc_File.cpp.i

.PHONY : qrc_File.i

# target to preprocess a source file
qrc_File.cpp.i:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.i
.PHONY : qrc_File.cpp.i

qrc_File.s: qrc_File.cpp.s

.PHONY : qrc_File.s

# target to generate assembly for a file
qrc_File.cpp.s:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.s
.PHONY : qrc_File.cpp.s

qrc_Input.o: qrc_Input.cpp.o

.PHONY : qrc_Input.o

# target to build an object file
qrc_Input.cpp.o:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.o
.PHONY : qrc_Input.cpp.o

qrc_Input.i: qrc_Input.cpp.i

.PHONY : qrc_Input.i

# target to preprocess a source file
qrc_Input.cpp.i:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.i
.PHONY : qrc_Input.cpp.i

qrc_Input.s: qrc_Input.cpp.s

.PHONY : qrc_Input.s

# target to generate assembly for a file
qrc_Input.cpp.s:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.s
.PHONY : qrc_Input.cpp.s

qrc_Triangulation_2.o: qrc_Triangulation_2.cpp.o

.PHONY : qrc_Triangulation_2.o

# target to build an object file
qrc_Triangulation_2.cpp.o:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.o
.PHONY : qrc_Triangulation_2.cpp.o

qrc_Triangulation_2.i: qrc_Triangulation_2.cpp.i

.PHONY : qrc_Triangulation_2.i

# target to preprocess a source file
qrc_Triangulation_2.cpp.i:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.i
.PHONY : qrc_Triangulation_2.cpp.i

qrc_Triangulation_2.s: qrc_Triangulation_2.cpp.s

.PHONY : qrc_Triangulation_2.s

# target to generate assembly for a file
qrc_Triangulation_2.cpp.s:
	$(MAKE) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.s
.PHONY : qrc_Triangulation_2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... CGAL_Qt5_moc_and_resources"
	@echo "... CGAL_Qt5_moc_and_resources_autogen"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qrc_CGAL.o"
	@echo "... qrc_CGAL.i"
	@echo "... qrc_CGAL.s"
	@echo "... qrc_File.o"
	@echo "... qrc_File.i"
	@echo "... qrc_File.s"
	@echo "... qrc_Input.o"
	@echo "... qrc_Input.i"
	@echo "... qrc_Input.s"
	@echo "... qrc_Triangulation_2.o"
	@echo "... qrc_Triangulation_2.i"
	@echo "... qrc_Triangulation_2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

